[package]
name = "timer"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.29.0", default-features = false }
human-errors = "0.1.5"
tokio = { version = "1.45.1", features = ["time", "rt", "macros", "signal"] }
